### ISSUE TITLE
Clarify in the STM docs that postcond is meant to test the pre-command state, not the post-command one

### ISSUE THREAD

**Issue by OlivierNicole** [jmid/multicoretests#102]
This week @ElectreAAS attempted to use STM to test her lock-free map, and we were both as confused with the results.

It turns out that we had a wrong `postcond`: we tried to check post-conditions on the state *after* running the command, whereas `postcond` can only check things on the input state.

This is stated in [the documentation of `postcond`](https://github.com/jmid/multicoretests/blob/2e922e4b62492616841077714fd81246e98a1e8d/lib/STM.ml#L96), but maybe we could make it extra clear somehow? (Actually, isn't the name `postcond` a tad confusing?)

In fact, is there a particular reason why `postcond` cannot take both the pre-command and post-command state as arguments? If we allowed it, we could let the users express more things in their postconditions.

**Comment by jmid** [comment]
> This is stated in the documentation of postcond, but maybe we could make it extra clear somehow? (Actually, isn't the name postcond a tad confusing?)

I agree that this is confusing and that making it even clearer would be helpful!
`postcond` expresses a property on the `res` obtained *after* a `cmd` has executed. In that sense, it is a post-condition.
Model-wise, the function takes "the old/pre state". Experience shows that this is helpful to model, e.g., a remove operation that returns the removed element. Furthermore, this is common in other state-machine frameworks IIRC.

> In fact, is there a particular reason why postcond cannot take both the pre-command and post-command state as arguments? > If we allowed it, we could let the users express more things in their postconditions.

Since `next_state` is supposed to be a pure state transition function, the post-command state should be obtainable by
```ocaml
  let post_state = next_state cmd pre_state
```
The reverse is not the case though (e.g., in a remove operation). As such, taking the `pre_state` is more expressive than taking the `post_state`, but taking both should not add expressivity AFAICS :man_shrugging:
